services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft
    hostname: minecraft
    restart: unless-stopped
    env_file: .env
    ports:
      - "19132:19132/udp"
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
